apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: demo-hauke
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"  # Regex f√ºr Pfade
spec:
  ingressClassName: nginx
  rules:
    - host: app.hauke.diogohack.shop
      http:
        paths:
          # Frontend auf /
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
          # Backend auf /api
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 3000
